CREATE TABLE IF NOT EXISTS members(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    groupName TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sets(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    memberId INTEGER NOT NULL,
    setId TEXT NOT NULL,
    setName TEXT NOT NULL,
    total INTEGER NOT NULL,
    releaseCode TEXT NOT NULL,
    FOREIGN KEY (memberId) REFERENCES members(id)
);

CREATE TABLE IF NOT EXISTS parts(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    setId INTEGER NOT NULL,
    partNumber INTEGER NOT NULL,
    owned INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (setId) REFERENCES sets(id)
);